// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmM4KL91hjuHnWdv8YUNCvNkNIZelZzj8',
    appId: '1:326208658236:android:ba43354624406f46595c39',
    messagingSenderId: '326208658236',
    projectId: 'words-e862a',
    databaseURL: 'https://words-e862a-default-rtdb.firebaseio.com',
    storageBucket: 'words-e862a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCICvpzz8dYU2GyU3O2QO9N82oRjYDHmhA',
    appId: '1:326208658236:ios:4ed8a6ce688664fa595c39',
    messagingSenderId: '326208658236',
    projectId: 'words-e862a',
    databaseURL: 'https://words-e862a-default-rtdb.firebaseio.com',
    storageBucket: 'words-e862a.appspot.com',
    iosClientId: '326208658236-acughab8dkrke9iujkbs5ethdab2cfb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.words',
  );
}
